# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tablenamesUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tablenameWindow(object):
    def setupUi(self, tablenameWindow):
        tablenameWindow.setObjectName("tablenameWindow")
        tablenameWindow.resize(530, 533)
        self.centralwidget = QtWidgets.QWidget(tablenameWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.nameList = QtWidgets.QListWidget(self.frame_3)
        self.nameList.setObjectName("nameList")
        self.horizontalLayout_2.addWidget(self.nameList)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.acceptNamesBtn = QtWidgets.QPushButton(self.frame_4)
        self.acceptNamesBtn.setObjectName("acceptNamesBtn")
        self.horizontalLayout_4.addWidget(self.acceptNamesBtn)
        self.discardNamesBtn = QtWidgets.QPushButton(self.frame_4)
        self.discardNamesBtn.setObjectName("discardNamesBtn")
        self.horizontalLayout_4.addWidget(self.discardNamesBtn)
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame)
        tablenameWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(tablenameWindow)
        QtCore.QMetaObject.connectSlotsByName(tablenameWindow)

    def retranslateUi(self, tablenameWindow):
        _translate = QtCore.QCoreApplication.translate
        tablenameWindow.setWindowTitle(_translate("tablenameWindow", "Zmień nazwy tabel"))
        self.label.setText(_translate("tablenameWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Zmień nazwy tabel</span></p></body></html>"))
        self.acceptNamesBtn.setText(_translate("tablenameWindow", "Zatwierdź nazwy tabel"))
        self.discardNamesBtn.setText(_translate("tablenameWindow", "Anuluj zmiany"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tablenameWindow = QtWidgets.QMainWindow()
    ui = Ui_tablenameWindow()
    ui.setupUi(tablenameWindow)
    tablenameWindow.show()
    sys.exit(app.exec_())
